// Code generated by "stringer -type Screen"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorScreen-0]
	_ = x[SplashScreen-1]
	_ = x[MenuScreen-2]
	_ = x[OptionsScreen-3]
	_ = x[PlayScreen-4]
	_ = x[InitScreen-5]
	_ = x[PauseScreen-6]
	_ = x[WinScreen-7]
	_ = x[LoseScreen-8]
}

const _Screen_name = "ErrorScreenSplashScreenMenuScreenOptionsScreenPlayScreenInitScreenPauseScreenWinScreenLoseScreen"

var _Screen_index = [...]uint8{0, 11, 23, 33, 46, 56, 66, 77, 86, 96}

func (i Screen) String() string {
	if i < 0 || i >= Screen(len(_Screen_index)-1) {
		return "Screen(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Screen_name[_Screen_index[i]:_Screen_index[i+1]]
}
