// Code generated by "stringer -type Screen"; DO NOT EDIT.

package screen

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Error-0]
	_ = x[Splash-1]
	_ = x[MainMenu-2]
	_ = x[Options-3]
	_ = x[Reset-4]
	_ = x[Play-5]
	_ = x[Pause-6]
	_ = x[Win-7]
	_ = x[Lose-8]
	_ = x[Exit-9]
}

const _Screen_name = "ErrorSplashMainMenuOptionsResetPlayPauseWinLoseExit"

var _Screen_index = [...]uint8{0, 5, 11, 19, 26, 31, 35, 40, 43, 47, 51}

func (i Screen) String() string {
	if i < 0 || i >= Screen(len(_Screen_index)-1) {
		return "Screen(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Screen_name[_Screen_index[i]:_Screen_index[i+1]]
}
